spring:
    application:
        name: AvroConsumer
    kafka:
        topic:
            orders: orders
        consumer:
            bootstrap-servers: localhost:9092
            schema:
                registry:
                    url: http://localhost:8081